[package]
name = "rgrep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1"
colored = "2"
walkdir = "2"
rayon = "1"

[dev-dependencies]
tempfile = "3"
